### ISSUE TITLE
Missing dependency management system for maintaining Go packages

### ISSUE THREAD

**Issue by PirosB3** [bitmark-inc/bitmarkd#5]
Bitmarkd depends on a series of other packages. Suggest to vendor these package and provide an easy way for installing, updating and maintaining them.
A good solution (also used in btcd) is [Glide](https://glide.sh/)

Here is a sample `glide.yaml` file.

```
package: github.com/bitmark-inc/bitmarkd/command/bitmarkd
import:
- package: github.com/bitmark-inc/bitmarkd
  version: v2.10
  subpackages:
  - announce
  - asset
  - block
  - chain
  - configuration
  - fault
  - mode
  - payment
  - payment/bitcoin
  - peer
  - proof
  - reservoir
  - rpc
  - storage
  - util
  - version
  - zmqutil
- package: github.com/bitmark-inc/certgen
- package: github.com/bitmark-inc/exitwithstatus
- package: github.com/bitmark-inc/getoptions
- package: github.com/bitmark-inc/listener
- package: github.com/bitmark-inc/logger
- package: golang.org/x/crypto
  subpackages:
  - sha3
```

Let me know if you would like my help with this.
